Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2022-10, with the labels that each got.

#2184 Mass histogram metadraw
  EngineLayer/PsmTsv/PsmFromTsv.cs
  EngineLayer/PsmTsv/PsmTsvReader.cs
  GUI/MetaDraw/MetaDraw.xaml.cs
  GuiFunctions/MetaDraw/PlotModelStat.cs
  Test/MetaDrawTest.cs
Labels: Bug, GUI, ready for review

#2182 File specific dissociation type
  EngineLayer/ProteinScoringAndFdr/ProteinScoringAndFdrEngine.cs
  GUI/Views/FileSpecificParametersWindow.xaml
  GUI/Views/FileSpecificParametersWindow.xaml.cs
  TaskLayer/FileSpecificParameters.cs
  Test/TestToml.cs
  Test/testFileSpecfic.toml
Labels: WIP

#2191 adjusted file specific parameters window
  GUI/Views/FileSpecificParametersWindow.xaml
Labels: Input Enhancement, User-Friendliness, ready for review

#2190 Hydrophobicity Histogram / Histogram Colors
  GuiFunctions/MetaDraw/PlotModelStat.cs
  Test/MetaDrawTest.cs
Labels: ready for review, ready for final review+merge

#2178 Fragment coverage of proteins
  EngineLayer/PeptideSpectralMatch.cs
  EngineLayer/ProteinParsimony/ProteinGroup.cs
  TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  Test/SeqCoverageTest.cs
  Test/StefanParsimonyTest.cs
  Test/TestPsm.cs
Labels: ready for review

#2193 Test Beta Release
  Test/SeqCoverageTest.cs
Labels: Validation, ready for review
