Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2022-06, with the labels that each got.

#2146 Edited PsmFromTsv to ignore enclosing quotes in fragment ion strings
  EngineLayer/PsmTsv/PsmFromTsv.cs
  Test/PsvTsvTest.cs
  Test/Test.csproj
  Test/TestData/ExcelEditedPeptide.psmtsv
  Test/XLTest.cs
  Test/XLTestOGlyco.cs
Labels: ready for final review+merge

#2129 Update references as citation guide; direct users to wiki in readme; list NET 6.0 requirement
  README.md
Labels: ready for review

#2155 update newtonsoftJson because of security concerns
  EngineLayer/EngineLayer.csproj
  GUI/GUI.csproj
Labels: ready for review, Security Vulnerability
