Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2023-01, with the labels that each got.

#2219 Removed Warnings in Meta Draw Plots
  GuiFunctions/MetaDraw/SpectrumMatch/ChimeraSpectrumMatchPlot.cs
  GuiFunctions/MetaDraw/SpectrumMatch/CrosslinkSpectrumMatchPlot.cs
  GuiFunctions/MetaDraw/SpectrumMatch/PeptideSpectrumMatchPlot.cs
  Test/MetaDrawSettingsAndViewsTest.cs
Labels: ready for review

#2213 Enable users to filter oxonium ions in ETD search
  EngineLayer/GlycoSearch/GlycoPeptides.cs
  EngineLayer/GlycoSearch/GlycoSearchEngine.cs
  Test/GlycoTestData/22-12-14_EclipseOglyco_EThcD_150ms_calRxn_17360.mgf
  Test/GlycoTestData/FiveMucinFasta.fasta
  Test/GlycoTestData/GlycoSearchTaskconfig_ETD.toml
  Test/Test.csproj
  Test/XLTestNGlyco.cs
  Test/XLTestOGlyco.cs
Labels: Bug, ready for review

#2220 warnings from old unit tests have crept into appveyor.
  EngineLayer/Mods/aListOfmods.txt
  GuiFunctions/MetaDraw/MetaDrawLogic.cs
  Test/CalibrationTests.cs
  Test/MetaDrawTest.cs
  Test/MsDataFileTest.cs
  Test/MyTaskTest.cs
  Test/SearchEngineTests.cs
  Test/SlicedSearchTaskConfig.toml
  Test/TestToml.cs
  Test/XLTest.cs
  Test/XLTestNGlyco.cs
  Test/gptmdPrunedBdTests.cs
Labels: Long-Term Stability, ready for review

#2222 Microsoft ml upgrade to version 2.0
  CMD/CMD.csproj
  EngineLayer/EngineLayer.csproj
  GUI/GUI.csproj
  MetaMorpheusSetup/Product.wxs
  TaskLayer/TaskLayer.csproj
  Test/Test.csproj
Labels: ready for review, dependencies

#2224 Upgrade to WiX4. Boostrapper1 and MetaMorpheusSetup
  Bootstrapper/Bootstrapper.wixproj
  Bootstrapper/bootstrapper.wxs
  Bootstrapper/theme.xml
  Bootstrapper1/Bootstrapper1.wixproj
  Bootstrapper1/bootstrapper1.wxs
  GUI/Views/MetaUpdater.xaml.cs
  MetaMorpheus.sln
  MetaMorpheusSetup/Maintenance.wxs
  MetaMorpheusSetup/MetaMorpheusSetup.wixproj
  MetaMorpheusSetup/MetaSCDlg.wxs
  MetaMorpheusSetup/Product.wxs
Labels: Maintenance, ready for review

#2223 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: ready for review
