Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2023-12, with the labels that each got.

#2318 Mzlib Update to 1.0.542 - Averaging crash fix+
  MetaMorpheus/CMD/CMD.csproj
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GUI/Util/Converters/AveragingTaskConverters.cs
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs
  MetaMorpheus/GuiFunctions/ViewModels/SpectralAveragingParametersViewModel.cs
  MetaMorpheus/TaskLayer/AveragingTask/SpectralAveragingTask.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/TaskLayer/TaskLayer.csproj
  MetaMorpheus/Test/AveragingGuiComponentsTest.cs
  MetaMorpheus/Test/AveragingTests.cs
  MetaMorpheus/Test/CompressionTest/tinySemiBroken.mgf
  MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/XLTestOGlyco.cs
  MetaMorpheus/Test/tinySemiBroken.mgf
Labels: Crash, ready for review, dependencies

#2321 bug fix Modification Info List which reports the the modification stoichiometry in PSM counts and fractions on the full protein sequence
  MetaMorpheus/EngineLayer/ProteinParsimony/ProteinGroup.cs
  MetaMorpheus/Test/ProteinGroupTest.cs
Labels: Bug

#2324 Hydroxy proline diagnostic ion error
  MetaMorpheus/EngineLayer/Mods/Mods.txt
Labels: Bug

#2292 Xl spectral library
  MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSpectralMatch.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmFromTsv.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvHeader.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvReader.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/CrosslinkLibrarySpectrum.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/LibrarySpectrum.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/SpectralLibrary.cs
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/CrosslinkSpectrumMatchPlot.cs
  MetaMorpheus/TaskLayer/XLSearchTask/PostXLSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/XLSearchTask/XLSearchParameters.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs
  MetaMorpheus/Test/PsvTsvTest.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/TestData/SpectralLibrarySearch/CrosslinkSpectralLibrary.msp
  MetaMorpheus/Test/XLSearchOutputTest.cs
  MetaMorpheus/Test/XLTest.cs
  MetaMorpheus/Test/XlTestData/2017-11-21_XL_DSSO_Ribosome_RT60min_28800-28898.mzML
  MetaMorpheus/Test/XlTestData/BSA_DSSO_SpectralLibrary.msp
  MetaMorpheus/Test/XlTestData/SinglePeptides.tsv
  MetaMorpheus/Test/XlTestData/XL_Interlinks.tsv
  MetaMorpheus/Test/XlTestData/XL_Intralinks.tsv
  MetaMorpheus/Test/XlTestData/XL_Intralinks_MIons.tsv
Labels: ready for review, ready for final review+merge

#2325 Hydroxy proline diagnostic ion error
  MetaMorpheus/EngineLayer/Mods/Mods.txt
Labels: Bug
