Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2024-11, with the labels that each got.

#2433 Update Numerical Inputs
  MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GlycoSearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/GlycoSearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/Util/DoubleTexBoxControl.cs
  MetaMorpheus/GUI/Util/IntegerTextBoxControl.cs
  MetaMorpheus/GUI/Views/FileSpecificParametersWindow.xaml
  MetaMorpheus/GUI/Views/FileSpecificParametersWindow.xaml.cs
Labels: GUI, Input Enhancement, Maintenance

#2426 Q value threshold adjustment and bug fix
  MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
  MetaMorpheus/TaskLayer/CalibrationTask/CalibrationTask.cs
  MetaMorpheus/Test/EverythingRunnerEngineTestCase.cs
  MetaMorpheus/Test/MatchIonsOfAllCharges.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs
  MetaMorpheus/Test/MetaDraw/SpectrumMatchPlotTests.cs
  MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs
  MetaMorpheus/Test/ProteinGroupTest.cs
  MetaMorpheus/Test/QuantificationTest.cs
  MetaMorpheus/Test/SearchEngineTests.cs
  MetaMorpheus/Test/SearchTaskTest.cs
  MetaMorpheus/Test/SilacTest.cs
  MetaMorpheus/Test/TestData/Task1-SearchTaskconfig.toml
  MetaMorpheus/Test/TestData/Task2-SearchTaskconfig.toml
  MetaMorpheus/Test/TestOGlyco.cs
  MetaMorpheus/Test/TestPsm.cs
  MetaMorpheus/Test/TestToml.cs
  MetaMorpheus/Test/XLTest.cs
Labels: Maintenance, ready for review

#2441 Mz lib553
  MetaMorpheus/CMD/CMD.csproj
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/EngineLayer/Ms2ScanWithSpecificMass.cs
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/TaskLayer/MbrAnalysis/SpectralRecoveryResults.cs
  MetaMorpheus/TaskLayer/MbrAnalysis/SpectralRecoveryRunner.cs
  MetaMorpheus/TaskLayer/TaskLayer.csproj
  MetaMorpheus/Test/CalibrationTests.cs
  MetaMorpheus/Test/SearchEngineTests.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/Test.csproj
Labels: dependencies
