Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2024-08, with the labels that each got.

#2383 Kdn adding and diagnostic filtering
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/EngineLayer/Glycan_Mods/OGlycan/OGlycan_withIsobaric.gdb
  MetaMorpheus/EngineLayer/GlycoSearch/AdjNode.cs
  MetaMorpheus/EngineLayer/GlycoSearch/Glycan.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycanBox.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycanDatabase.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoPeptides.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoSearchEngine.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoSpectralMatch.cs
  MetaMorpheus/EngineLayer/GlycoSearch/LocalizationGraph.cs
  MetaMorpheus/EngineLayer/GlycoSearch/ModBox.cs
  MetaMorpheus/EngineLayer/GlycoSearch/Node.cs
  MetaMorpheus/EngineLayer/ModernSearch/ModernSearchEngine.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmFromTsv.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/GlycoSearchTask.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/PostGlycoSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/WriteGlycoFile.cs
  MetaMorpheus/Test/GlycoTestData/GlycoSearchTaskconfigNGlycoTest_Run.toml
  MetaMorpheus/Test/GlycoTestData/GlycoSearchTaskconfigN_OGlycoTest_Run.toml
  MetaMorpheus/Test/GlycoTestData/Glyco_Isobaric_testing.toml
  MetaMorpheus/Test/MetaDraw/MetaDrawSettingsAndViewsTest.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/TestNGlyco.cs
  MetaMorpheus/Test/TestOGlyco.cs
Labels: ready for review

#2387 Changes to PEP Calculation and Filtering
  MetaMorpheus/EngineLayer/ClassicSearch/ClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/CommonParameters.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/PEPValueAnalysisGeneric.cs
  MetaMorpheus/EngineLayer/NonSpecificEnzymeSearch/NonSpecificEnzymeSearchEngine.cs
  MetaMorpheus/EngineLayer/ProteinParsimony/ProteinParsimonyEngine.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvWriter.cs
  MetaMorpheus/EngineLayer/SpectralMatch.cs
  MetaMorpheus/TaskLayer/FilteredPsms.cs
  MetaMorpheus/TaskLayer/MbrAnalysis/SpectralRecoveryRunner.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/TaskLayer/MyTaskResults.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/Test/FdrTest.cs
  MetaMorpheus/Test/MultiProteaseParsimonyTest.cs
  MetaMorpheus/Test/MyTaskTest.cs
  MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs
  MetaMorpheus/Test/SearchEngineTests.cs
  MetaMorpheus/Test/SearchTaskTest.cs
  MetaMorpheus/Test/SilacTest.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/TestDataFile.cs
  MetaMorpheus/Test/TestPsm.cs
Labels: Validation, ready for review

#2367 Add the comment on glyco-searching and the search summary on the result file
  MetaMorpheus/Test/TestOGlyco.cs
Labels: Output Enhancement, Documentation, ready for review

#2398 Github Actions 1: Cross Platform Build
  .github/workflows/build.yml
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/MetaMorpheus.sln
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/Test.csproj
Labels: Long-Term Stability, ready for review

#2403 Polishing prose
  MetaMorpheus/EngineLayer/PrecursorSearchModes/DotMassDiffAcceptor.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
Labels: ready for review

#2404 update mzlib nuget package to 551
  MetaMorpheus/CMD/CMD.csproj
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/TaskLayer/TaskLayer.csproj
  MetaMorpheus/Test/Test.csproj
Labels: dependencies
