Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2024-06, with the labels that each got.

#2370 Spectral Averaging Command Line
  MetaMorpheus/CMD/Program.cs
Labels: New Feature, CMD, ready for review

#2371 Cross Link Spectrum Match Plot Export Bug Fix
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/CrosslinkSpectrumMatchPlot.cs
  MetaMorpheus/Test/MetaDraw/SpectrumMatchPlotTests.cs
Labels: Bug, ready for review, Visualization

#2372 Stop scrolling of progress bar after calculating spectral angle
  MetaMorpheus/TaskLayer/SearchTask/SearchTask.cs
Labels: Bug, GUI, Maintenance, ready for review

#2373 Pep on peptides first
  MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/PEPValueAnalysisGeneric.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/Test/FdrTest.cs
  MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/TestData/SpectralRecoveryTest/AllPSMsTesting.psmtsv
  MetaMorpheus/Test/TestData/SpectralRecoveryTest/HumanFastaSlice.fasta
  MetaMorpheus/Test/TestData/SpectralRecoveryTest/MsMsids.psmtsv
Labels: Performance, Maintenance, ready for review

#2361 MetaDraw Fragmentation Reanalysis
  MetaMorpheus/EngineLayer/PsmTsv/PsmFromTsv.cs
  MetaMorpheus/GUI/MetaDraw/MetaDraw.xaml
  MetaMorpheus/GUI/MetaDraw/MetaDraw.xaml.cs
  MetaMorpheus/GUI/Views/FragmentReanalysisControl.xaml
  MetaMorpheus/GUI/Views/FragmentReanalysisControl.xaml.cs
  MetaMorpheus/GuiFunctions/MetaDraw/DrawnSequence.cs
  MetaMorpheus/GuiFunctions/MetaDraw/FragmentResearching/FragmentViewModel.cs
  MetaMorpheus/GuiFunctions/MetaDraw/FragmentResearching/FragmentationReanalysisViewModel.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawSettings.cs
  MetaMorpheus/Test/MetaDraw/FragmentReanalysis.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawSettingsAndViewsTest.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/TestData/S.m,al. lC,al.ib r.at,i ble_Ye.ast.mzML
Labels: New Feature, ready for review, Visualization

#2378 Added some tooltips for the cross link search task view.
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml
Labels: User-Friendliness, ready for review
