Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2024-12, with the labels that each got.

#2449 round calibration tolerance to one decimal place
  MetaMorpheus/TaskLayer/CalibrationTask/CalibrationTask.cs
Labels: Long-Term Stability, ready for review

#2434 Analyte type
  MetaMorpheus/EngineLayer/AnalyteType.cs
  MetaMorpheus/EngineLayer/GlobalVariables.cs
  MetaMorpheus/MetaMorpheus.sln.DotSettings
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/Test/GlobalVariablesTest.cs
  MetaMorpheus/Test/MatchIonsOfAllCharges.cs
  MetaMorpheus/Test/TestTopDown.cs
Labels: New Feature, ready for review, Refactor

#2453 nonspecific search engine bug fix and unit test
  MetaMorpheus/EngineLayer/NonSpecificEnzymeSearch/NonSpecificEnzymeSearchEngine.cs
  MetaMorpheus/Test/SearchEngineTests.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/TestData/NonSpecificSearchToml.toml
  MetaMorpheus/Test/TestData/bosTaurusEnamPruned.xml
Labels: Crash, Bug, ready for review

#2451 MzLib 1.0.545
  MetaMorpheus/CMD/CMD.csproj
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/TaskLayer/TaskLayer.csproj
  MetaMorpheus/Test/Test.csproj
Labels: ready for review, dependencies
