Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2024-02, with the labels that each got.

#2338 Eliminate delta score option
  MetaMorpheus/EngineLayer/CommonParameters.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/Test/FdrTest.cs
  MetaMorpheus/Test/ParameterTest.cs
  MetaMorpheus/Test/gptmdPrunedBdTests.cs
Labels: Discussion, Long-Term Stability, Maintenance, ready for review

#2336 Add leucine to chymotrypsin cleavage motifs
  MetaMorpheus/EngineLayer/ProteolyticDigestion/proteases.tsv
  MetaMorpheus/Test/DatabaseTests/Q9UHB6.FASTA
  MetaMorpheus/Test/DatabaseTests/Q9UHB6_Chym_snip.mzML
  MetaMorpheus/Test/DatabaseTests/Task1-SearchTaskconfig.toml
  MetaMorpheus/Test/ProteaseTests.cs
  MetaMorpheus/Test/Test.csproj
Labels: Bug, ready for review

#2322 N-glyco search improvements
  MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoSpectralMatch.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/PostGlycoSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/WriteGlycoFile.cs
  MetaMorpheus/TaskLayer/XLSearchTask/PostXLSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/XLSearchTask/WriteXlFile.cs
  MetaMorpheus/Test/OutputTest.cs
  MetaMorpheus/Test/TestNGlyco.cs
  MetaMorpheus/Test/TestOGlyco.cs
  MetaMorpheus/Test/XLTest.cs
Labels: Bug, ready for review

#2343 Pass dissociation type not autodetect to diss type collection
  MetaMorpheus/TaskLayer/SearchTask/SearchTask.cs
Labels: Bug, ready for review

#2342 Added console output before and after uniprot tests
  MetaMorpheus/Test/GuiFunctionsTest.cs
Labels: ready for review

#2349 use mzlib LibrarySpectrum class
  MetaMorpheus/EngineLayer/PsmTsv/PsmFromTsv.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/CrosslinkLibrarySpectrum.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/LibrarySpectrum.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/SpectralLibrary.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/SpectralLibrarySearchFunction.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/CrosslinkSpectrumMatchPlot.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/PeptideSpectrumMatchPlot.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/SpectrumMatchPlot.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/XLSearchTask/PostXLSearchAnalysisTask.cs
  MetaMorpheus/Test/MatchIonsOfAllCharges.cs
Labels: Bug, ready for review

#2350 Update .NET version in readme
  README.md
Labels: ready for review

#2339 #2- Deconvolution Generalization
  MetaMorpheus/EngineLayer/CommonParameters.cs
  MetaMorpheus/EngineLayer/Ms2ScanWithSpecificMass.cs
  MetaMorpheus/GUI/Views/CustomFragmentationWindow.xaml.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/Transcriptomics/TestData/GUACUG_NegativeMode_Sliced.mzML
  MetaMorpheus/Test/Transcriptomics/TestNegativeModeDeconvolution.cs
Labels: Bug, ready for review, Refactor
