Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2024-10, with the labels that each got.

#2421 Eliminate those pesky warnings
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvReader.cs
  MetaMorpheus/GuiFunctions/MetaDraw/FragmentResearching/FragmentationReanalysisViewModel.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawSettings.cs
  MetaMorpheus/GuiFunctions/ViewModels/SpectralAveragingParametersViewModel.cs
  MetaMorpheus/MetaMorpheus.sln.DotSettings
  MetaMorpheus/TaskLayer/AveragingTask/SpectralAveragingTask.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/PostGlycoSearchAnalysisTask.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/TestDataFile.cs
  MetaMorpheus/Test/XLTest.cs
Labels: Maintenance

#2423 Soften calibration tolerance
  MetaMorpheus/EngineLayer/Calibration/CalibrationEngine.cs
  MetaMorpheus/EngineLayer/Calibration/DataPointAcquisitionEngine.cs
  MetaMorpheus/EngineLayer/Calibration/DataPointAquisitionResults.cs
  MetaMorpheus/GUI/MainWindow.xaml.cs
  MetaMorpheus/TaskLayer/CalibrationTask/CalibrationTask.cs
  MetaMorpheus/Test/CalibrationTests.cs
  MetaMorpheus/Test/Test.csproj
  MetaMorpheus/Test/TestData/SmallCalibratible_Yeast.toml
Labels: Maintenance, WIP

#2430 Updated FilteredPsms to only iterate through PSMs once
  MetaMorpheus/TaskLayer/FilteredPsms.cs
Labels: Refactor
