Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2025-03, with the labels that each got.

#2478 Scan with index and notch update
  MetaMorpheus/EngineLayer/ClassicSearch/ClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/ClassicSearch/MiniClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/ScanWithIndexAndNotchInfo.cs
  MetaMorpheus/EngineLayer/Util/ScanWithIndexAndNotchInfo.cs
  MetaMorpheus/Test/XLTest.cs
Labels: Maintenance, ready for review

#2481 Added user specified proteome directory to global gui settings
  MetaMorpheus/GUI/MainWindow.xaml.cs
  MetaMorpheus/GUI/Util/GuiGlobalParams.cs
  MetaMorpheus/GUI/Util/UpdateGUISettings.cs
  MetaMorpheus/MetaMorpheus.sln.DotSettings
Labels: GUI, Maintenance, ready for review

#2486 Hotfix: IsoDec and other Missing dlls :(
  MetaMorpheus/MetaMorpheusSetup/Product.wxs
  MetaMorpheus/Test/SearchEngineTests.cs
Labels: Crash, Bug, ready for review, dependencies

#2488 Create Testing Github Action
  .github/workflows/Test.yml
Labels: Long-Term Stability, ready for review

#2483 Spectral Match Hypothesis
  MetaMorpheus/EngineLayer/BioPolymerNotchFragmentIonComparer.cs
  MetaMorpheus/EngineLayer/Calibration/DataPointAcquisitionEngine.cs
  MetaMorpheus/EngineLayer/ClassicSearch/MiniClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSpectralMatch.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/PEPAnalysisEngine.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoSearchEngine.cs
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoSpectralMatch.cs
  MetaMorpheus/EngineLayer/Gptmd/GptmdEngine.cs
  MetaMorpheus/EngineLayer/Localization/LocalizationEngine.cs
  MetaMorpheus/EngineLayer/ModificationAnalysis/ModificationAnalysisEngine.cs
  MetaMorpheus/EngineLayer/OligoSpectralMatch.cs
  MetaMorpheus/EngineLayer/PeptideSpectralMatch.cs
  MetaMorpheus/EngineLayer/ProteinParsimony/ProteinGroup.cs
  MetaMorpheus/EngineLayer/ProteinParsimony/ProteinParsimonyEngine.cs
  MetaMorpheus/EngineLayer/ProteinScoringAndFdr/ProteinScoringAndFdrEngine.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvWriter.cs
  MetaMorpheus/EngineLayer/Silac/SilacConversions.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/SpectralLibrarySearchFunction.cs
  MetaMorpheus/EngineLayer/SpectralMatch.cs
  MetaMorpheus/EngineLayer/SpectrumMatch/ISearchAttempt.cs
  MetaMorpheus/EngineLayer/SpectrumMatch/SpectralMatchHypothesis.cs
  MetaMorpheus/EngineLayer/Util/DictionaryExtensions.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/PostGlycoSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/MbrAnalysis/SpectralRecoveryRunner.cs
  MetaMorpheus/TaskLayer/PepXMLWriter.cs
  MetaMorpheus/TaskLayer/SearchTask/MzIdentMLWriter.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/SearchTask/SearchTask.cs
  MetaMorpheus/TaskLayer/XLSearchTask/WriteXlFile.cs
  MetaMorpheus/TaskLayer/XLSearchTask/XLSearchTask.cs
  MetaMorpheus/Test/DictionaryExtensionsTests.cs
  MetaMorpheus/Test/FdrTest.cs
  MetaMorpheus/Test/GlobalVariablesTest.cs
  MetaMorpheus/Test/MatchIonsOfAllCharges.cs
  MetaMorpheus/Test/PsmTsvWriterTests.cs
  MetaMorpheus/Test/RobTest.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/TestPsm.cs
  MetaMorpheus/Test/UtilitiesTest/BioPolymerNotchFragmentIonComparerFromFromSpectralMatchHypothesisTest.cs
  MetaMorpheus/Test/UtilitiesTest/BioPolymerNotchFragmentIonComparerTest.cs
  MetaMorpheus/Test/UtilitiesTest/SpectralMatchHypothesisTests.cs
  MetaMorpheus/Test/XLTest.cs
Labels: Maintenance, ready for review, Refactor

#2491 Refactored GPTMD to use scan array
  MetaMorpheus/EngineLayer/Gptmd/GptmdEngine.cs
  MetaMorpheus/EngineLayer/ModernSearch/ModernSearchEngine.cs
  MetaMorpheus/EngineLayer/Util/DictionaryExtensions.cs
  MetaMorpheus/TaskLayer/GPTMDTask/GPTMDTask.cs
  MetaMorpheus/Test/GPTMDengineTest.cs
Labels: ready for review

#2476 Remove datascan
  MetaMorpheus/EngineLayer/SpectralMatch.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/Test/Multiplex_Labeling_TMT_iTRAQ.cs
Labels: Performance, ready for review, Refactor

#2494 Refactoring to use IIndexedMzPeak
  MetaMorpheus/CMD/CMD.csproj
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/EngineLayer/Silac/SilacConversions.cs
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/TaskLayer/TaskLayer.csproj
  MetaMorpheus/Test/Test.csproj
Labels: Refactor
