Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2025-08, with the labels that each got.

#2548 Refactor : Include the localization probability into the ModSitePair class as a new property
  MetaMorpheus/EngineLayer/GlycoSearch/GlycoSpectralMatch.cs
  MetaMorpheus/EngineLayer/GlycoSearch/LocalizationGraph.cs
  MetaMorpheus/EngineLayer/GlycoSearch/Route.cs
  MetaMorpheus/EngineLayer/ModSearch/ModSitePair.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/GlycoProteinParsimony.cs
  MetaMorpheus/TaskLayer/GlycoSearchTask/GlycoSearchTask.cs
  MetaMorpheus/Test/TestOGlyco.cs
Labels: ready for review, Refactor

#2552 Add precursor and MS2 scan counts for all files and individual files to Results.txt
  MetaMorpheus/EngineLayer/Util/AnalyteType.cs
  MetaMorpheus/TaskLayer/MyFileManager.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisParameters.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/SearchTask/SearchTask.cs
  MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs
  MetaMorpheus/Test/SearchTaskTest.cs
Labels: Output Enhancement, ready for review

#2560 Docker file update
  .github/workflows/DockerUpload.yml
  MetaMorpheus/Dockerfile
  MetaMorpheus/Dockerfile_WindowsInstaller
Labels: Packaging/Distributing, Maintenance, ready for review

#2549 Remove library from MetaMorpheus
  MetaMorpheus/EngineLayer/ClassicSearch/ClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/ClassicSearch/MiniClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/SpectralLibrary.cs
  MetaMorpheus/EngineLayer/SpectralLibrarySearch/SpectralLibrarySearchFunction.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs
  MetaMorpheus/TaskLayer/MbrAnalysis/SpectralRecoveryRunner.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisParameters.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/Test/MatchIonsOfAllCharges.cs
  MetaMorpheus/Test/SpectralLibraryReaderTest.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
  MetaMorpheus/Test/XLSearchOutputTest.cs
Labels: ready for review, Refactor

#2561 Update InstallRunAndArtifact.yml
  .github/workflows/BuildReleaseArtifact.yml
  .github/workflows/InstallRunAndArtifact.yml
Labels: Packaging/Distributing, ready for review
