Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2025-02, with the labels that each got.

#2459 Added Decon Parameters to Calibration Window
  MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GlycoSearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml.cs
Labels: GUI, New Feature, ready for review

#2464 Updated mzLib versoin
  MetaMorpheus/CMD/CMD.csproj
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/GUI/GUI.csproj
  MetaMorpheus/GuiFunctions/GuiFunctions.csproj
  MetaMorpheus/TaskLayer/TaskLayer.csproj
  MetaMorpheus/Test/Test.csproj
Labels: ready for review

#2463 Model lock
  MetaMorpheus/EngineLayer/FdrAnalysis/PEPAnalysisEngine.cs
  MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs
  MetaMorpheus/Test/TestData/Task1-SearchTaskconfig.toml
Labels: ready for review

#2460 Optional Digestion Count Output
  MetaMorpheus/EngineLayer/ClassicSearch/ClassicSearchEngine.cs
  MetaMorpheus/EngineLayer/Util/AnalyteType.cs
  MetaMorpheus/EngineLayer/Util/DictionaryExtensions.cs
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/SearchTask/SearchParameters.cs
  MetaMorpheus/TaskLayer/SearchTask/SearchTask.cs
  MetaMorpheus/Test/DictionaryExtensionsTests.cs
  MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs
Labels: Output Enhancement, New Feature, ready for review

#2442 IsoDec incorporation
  MetaMorpheus/EngineLayer/CommonParameters.cs
  MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/Util/Converters/DeconvolutionTypeToControlConverter.cs
  MetaMorpheus/GUI/Views/Deconvolution/HostDeconParamControl.xaml
  MetaMorpheus/GUI/Views/Deconvolution/IsoDecDeconParamControl.xaml
  MetaMorpheus/GUI/Views/Deconvolution/IsoDecDeconParamControl.xaml.cs
  MetaMorpheus/GuiFunctions/MzLibExtensions.cs
  MetaMorpheus/GuiFunctions/ViewModels/BaseViewModel.cs
  MetaMorpheus/GuiFunctions/ViewModels/Deconvolution/DeconHostViewModel.cs
  MetaMorpheus/GuiFunctions/ViewModels/Deconvolution/DeconParamsViewModel.cs
  MetaMorpheus/GuiFunctions/ViewModels/Deconvolution/IsoDecDeconParamsViewModel.cs
  MetaMorpheus/MetaMorpheus.sln.DotSettings
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/Test/GuiTests/DeconHostViewModelTest.cs
  MetaMorpheus/Test/GuiTests/DeconParamsViewModelTest.cs
  MetaMorpheus/Test/GuiTests/IsoDecDeconParamsViewModelTest.cs
  MetaMorpheus/Test/GuiTests/MzLibExtensionsTests.cs
  MetaMorpheus/Test/SearchTaskTest.cs
Labels: New Feature, ready for review

#2455 Stability Update
  MetaMorpheus/EngineLayer/Calibration/DataPointAcquisitionEngine.cs
  MetaMorpheus/EngineLayer/FdrAnalysis/SpectralMatchGroup.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/TaskLayer/MyFileManager.cs
  MetaMorpheus/TaskLayer/SearchTask/SearchTask.cs
  MetaMorpheus/Test/EverythingRunnerEngineTestCase.cs
  MetaMorpheus/Test/XLSearchOutputTest.cs
  MetaMorpheus/Test/XLTest.cs
Labels: Bug, ready for review

#2465 Resolve ions
  MetaMorpheus/EngineLayer/BioPolymerNotchFragmentIonComparer.cs
  MetaMorpheus/EngineLayer/SpectralMatch.cs
  MetaMorpheus/Test/BioPolymerNotchFragmentIonComparerTest.cs
  MetaMorpheus/Test/TestPsm.cs
Labels: ready for review

#2468 Made updates pertaining to PIP-ECHO
  MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/GlycoSearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml
  MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml.cs
  MetaMorpheus/GUI/Util/GlobalGuiSettings.cs
  MetaMorpheus/TaskLayer/FilteredPsms.cs
  MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs
  MetaMorpheus/TaskLayer/SearchTask/SearchParameters.cs
Labels: ready for review

#2474 a calibration task that potentially works
  MetaMorpheus/TaskLayer/CalibrationTask/CalibrationTask.cs
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
  MetaMorpheus/Test/CalibrationRetainsProperTolerances.cs
  MetaMorpheus/Test/CalibrationTests.cs
  MetaMorpheus/Test/MyTaskTest.cs
Labels: Bug, ready for review

#2470 New HotKeys for GUI
  MetaMorpheus/GUI/MainWindow.xaml
  MetaMorpheus/GUI/MainWindow.xaml.cs
Labels: GUI, User-Friendliness, ready for review
