Repository smith-chem-wisc/MetaMorpheus, pull requests merged in 2025-05, with the labels that each got.

#2489 Create Install and Run Github Action
  .github/workflows/InstallRunAndArtifact.yml
  MetaMorpheus/MetaMorpheusSetup/Product.wxs
Labels: Long-Term Stability, ready for review

#2505 Uncommented try/catch statement in MetaMorpheus Task
  MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
Labels: Bug, ready for review

#2509 Update InstallRunAndArtifact.yml
  .github/workflows/InstallRunAndArtifact.yml
Labels: Bug, Packaging/Distributing, ready for review

#2507 Protein output fix
  MetaMorpheus/EngineLayer/ProteinParsimony/ProteinGroup.cs
  MetaMorpheus/Test/ProteinGroupTest.cs
Labels: Bug, ready for review

#2508 Rna Modifications
  MetaMorpheus/EngineLayer/EngineLayer.csproj
  MetaMorpheus/EngineLayer/GlobalVariables.cs
  MetaMorpheus/EngineLayer/Mods/RnaMods.txt
  MetaMorpheus/MetaMorpheus.sln.DotSettings
  MetaMorpheus/Test/Transcriptomics/RnaModLoadingTests.cs
Labels: New Feature, ready for review

#2512 Use MzLib.Readers for PSM Header and all parsing
  MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSpectralMatch.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmFromTsv.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvHeader.cs
  MetaMorpheus/EngineLayer/PsmTsv/PsmTsvReader.cs
  MetaMorpheus/EngineLayer/SpectrumMatch/PsmTsvWriter.cs
  MetaMorpheus/Test/AmbiguityTest.cs
  MetaMorpheus/Test/PsmTsvWriterTests.cs
  MetaMorpheus/Test/TestPsm.cs
Labels: Long-Term Stability, Maintenance, ready for review

#2506 Generalize MetaDraw to use SpectrumMatchFromTsv
  MetaMorpheus/GUI/MetaDraw/MetaDraw.xaml.cs
  MetaMorpheus/GuiFunctions/MetaDraw/DrawnSequence.cs
  MetaMorpheus/GuiFunctions/MetaDraw/FragmentResearching/FragmentationReanalysisViewModel.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs
  MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawSettings.cs
  MetaMorpheus/GuiFunctions/MetaDraw/PlotModelStat.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/ChimeraSpectrumMatchPlot.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/PeptideSpectrumMatchPlot.cs
  MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/SpectrumMatchPlot.cs
  MetaMorpheus/GuiFunctions/MzLibExtensions.cs
  MetaMorpheus/GuiFunctions/ViewModels/Legends/ChimeraLegendViewModel.cs
  MetaMorpheus/GuiFunctions/ViewModels/Legends/PtmLegendViewModel.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawSettingsAndViewsTest.cs
  MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs
  MetaMorpheus/Test/MetaDraw/SpectrumMatchPlotTests.cs
  MetaMorpheus/Test/PsvTsvTest.cs
  MetaMorpheus/Test/SearchEngineTests.cs
  MetaMorpheus/Test/SpectralRecoveryTest.cs
Labels: Input Enhancement, Maintenance, ready for review

#2514 Fix Glyco Crash on ProteinParsimony
  MetaMorpheus/EngineLayer/ProteinParsimony/ProteinParsimonyEngine.cs
Labels: Crash, Bug, ready for review
